FROM python:3.10

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# This is the command that starts your FastAPI server
CMD ["python", "main.py"]
